/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE course-materialsBaseService PLEASE EDIT ../course-materials.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { CourseMaterials } from '../../domain/mentoring_db/course-materials';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../courseMaterials.service.ts
 */

/*
 * SCHEMA DB courseMaterials
 *
	{
		Instructor: {
			type: 'String',
			required : true
		},
		Material: {
			type: 'String',
			required : true
		},
		Name: {
			type: 'String',
			required : true
		},
		Session: {
			type: 'Number',
			required : true
		},
		Subject: {
			type: 'String',
			required : true
		},
		id: {
			type: 'Number',
			required : true
		},
		sessionId: {
			type: 'Number',
			required : true
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		_courseMaterials: {
			type: Schema.ObjectId,
			ref : "session_01"
		},
		_instructor: [{
			type: Schema.ObjectId,
			ref : "courseMaterials"
		}],
		_session_01: [{
			type: Schema.ObjectId,
			ref : "courseMaterials"
		}],
		_test: {
			type: Schema.ObjectId,
			ref : "courseMaterials"
		},
	}
 *
 */
@Injectable()
export class CourseMaterialsBaseService {

    contextUrl: string = environment.endpoint + '/coursematerials';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS


    // Custom APIs

}
