/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE session_01BaseService PLEASE EDIT ../session_01.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Session_01 } from '../../domain/mentoring_db/session_01';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../session_01.service.ts
 */

/*
 * SCHEMA DB session_01
 *
	{
		Duration: {
			type: 'Date',
			required : true
		},
		Goal: {
			type: 'String',
			required : true
		},
		Instructor: {
			type: 'String',
			required : true
		},
		Title: {
			type: 'String',
			required : true
		},
		task: {
			type: 'Number',
			required : true
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		_course: {
			type: Schema.ObjectId,
			ref : "session_01"
		},
		_courseMaterials: {
			type: Schema.ObjectId,
			ref : "session_01"
		},
		_session_01: [{
			type: Schema.ObjectId,
			ref : "courseMaterials"
		}],
	}
 *
 */
@Injectable()
export class Session_01BaseService {

    contextUrl: string = environment.endpoint + '/session_01';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS


    // Custom APIs

}
