/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|


 * DO NOT EDIT THIS FILE!!
 *
 *  TO CUSTOMIZE courseMaterialsBase PLEASE EDIT ../course-materials.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
import { Exam } from '../exam';

/**
 * This is the model of courseMaterials object
 *
 */
export class CourseMaterialsBase {

    constructor() { }

    public _id: string;
    public Instructor: string;
    public Material: string;
    public Name: string;
    public Session: number;
    public Subject: string;
    public id: number;
    public sessionId: number;
    // Relations _test
    public _test: Exam | string;
    // Relations m:m _instructor
    public _instructor: string[];
    // Relations m:m _session_01
    public _session_01: string[];
}
