/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|


 * DO NOT EDIT THIS FILE!!
 *
 *  TO CUSTOMIZE session_01Base PLEASE EDIT ../session_01.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
import { Course } from '../course';
import { CourseMaterials } from '../course-materials';

/**
 * This is the model of session_01 object
 *
 */
export class Session_01Base {

    constructor() { }

    public _id: string;
    public Duration: Date;
    public Goal: string;
    public Instructor: string;
    public Title: string;
    public task: number;
    // Relations _course
    public _course: Course | string;
    // Relations _courseMaterials
    public _courseMaterials: CourseMaterials | string;
}
